Gemfile, Gemfile.lock, app/controllers/api/registrations_controller.rb, app/controllers/api/sessions_controller.rb, app/models/user.rb, config/database.yml, config/routes.rb, db/migrate/20200813130425_add_authentication_token_to_users.rb, db/schema.rb
- [A2R-7](https://smashingboxes.atlassian.net/browse/A2R-7)
- [A2R-6](https://smashingboxes.atlassian.net/browse/A2R-6)
- Created Login User API where the user will send their email and password for the backend API to respond with an auth token.
- Created Register User API where the user will send their name, email, and password for the backend to create the associated record ad will return the user's information along with the generated auth token.
- Added "generate_token" method inside user.rb file to generate authentication_token for user when the record is created.
User Login API
Users Registration API
=> User Login and Registration APIs

app/controllers/api/mail_templates_controller.rb, app/models/mail_template.rb, config/routes.rb
- [A2R-63](https://smashingboxes.atlassian.net/browse/A2R-63)
- Added API to create Mail Templates.
- Added API to update existing Mail Template.
- Added API to destroy existing Mail Template
Mail Template Create API
Mail Template Update API
Mail Template Destroy API
=> NR_A2R_63: Back End Email Template

app/controllers/api/results_controller.rb, app/models/result.rb, config/routes.rb
- [A2R-77](https://smashingboxes.atlassian.net/browse/A2R-77)
- Created API to fetch user's "Your Information" for the currently started CTR.
- Created API to Update user's "Your Information" for the currently started CTR.
Fetch User Your Information API
Update User Your Information API
=> NR_A2R_77: Back End - Your Information

config/environments/production.rb
Fix deployment configurations and compiling assets
=> Fix heroku deployment

app/controllers/api/results_controller.rb, app/models/result.rb, config/routes.rb
- [A2R-78](https://smashingboxes.atlassian.net/browse/A2R-78)
- Created API to fetch user's "Author Summary" for the currently started CTR.
- Created API to Update user's "Author Summary" for the currently started CTR.
Fetch User Author Summary API
Update User Author Summary API
=> NR_A2R_78: Back End Author Summary

app/controllers/api/results_controller.rb, app/models/result.rb, config/routes.rb
- [A2R-79](https://smashingboxes.atlassian.net/browse/A2R-79)
- Created API to fetch user's "Trial Information" for the currently started CTR.
- Created API to Update user's "Trial Information" for the currently started CTR.
- Created API to fetch Trial Information's dropdown lists
Fetch User Trial Information API
Fetch User Trial Information Lists API
Update User Trial Information API
=> NR_A2R_79: Back End Trial Information

app/models/result.rb
=> Left a comment to add more comments to the code

app/controllers/api/results_controller.rb, app/models/result.rb, app/models/user.rb, config/routes.rb
- [A2R-80](https://smashingboxes.atlassian.net/browse/A2R-80)
- Created API to fetch user's "Coauthor Information" for the currently started CTR.
- Created API to Update user's "Coauthor Information" for the currently started CTR.
Fetch User Coauthor Information API
Update User Coauthor Information API
=> NR_A2R_80: Back-end Coauthor Information

app/assets/javascripts/comments.coffee, app/assets/stylesheets/comments.scss, app/controllers/comments_controller.rb, app/controllers/devise/registrations_controller.rb, app/helpers/comments_helper.rb, app/models/comment.rb, app/models/result.rb, app/models/user.rb, app/views/comments/_comment.json.jbuilder, app/views/comments/_form.html.erb, app/views/comments/edit.html.erb, app/views/comments/index.html.erb, app/views/comments/index.json.jbuilder, app/views/comments/new.html.erb, app/views/comments/show.html.erb, app/views/comments/show.json.jbuilder, config/routes.rb, test/controllers/comments_controller_test.rb, test/fixtures/comments.yml, test/models/comment_test.rb, test/system/comments_test.rb
- Created API to Create comment for the specific "step" for CTR.
- Created API to Update a comment for a specific "step" for CTR.
- Added the comments to return API for each steps for CTR.
- Added validation for User Registration where it will check if email is already used or not.
Comment Create API
Comment Update API
User Registration API
Fetch CTR (Result) Overview API
=> NR_CTR_Comments_API

app/controllers/api/results_controller.rb, app/models/arm.rb, app/models/drug.rb, app/models/result.rb, config/routes.rb
- [A2R-89](https://smashingboxes.atlassian.net/browse/A2R-89)
- Created API to fetch user's "Drug Information" for the currently started CTR.
- Created API to Update user's "Drug Information" for the currently started CTR.
Fetch User Drug Information API
Update User Drug Information API
=> NR_A2R_89: Back End Drug Information

app/controllers/api/results_controller.rb, app/models/result.rb
- Added result_id as parameter for fetching and updating CTR steps to search CTR (Result) using the result id.
- Added key_words parameter for Fetch and Update CTR Overview APIs since it was missing in the previous build.
=> NR_CTR_Fetch_API

app/controllers/api/results_controller.rb, app/models/arm.rb, app/models/result.rb, config/routes.rb
- [A2R-87](https://smashingboxes.atlassian.net/browse/A2R-87)
- Created API to fetch user's "Patient Characteristics" for CTR.
- Created API to Update user's "Patient Characteristics" for CTR.
Fetch User CTR Patient Characteristics API
Update User CTR Patient Characteristics API
=> NR_A2R_87: Back End Patient Characteristics

app/controllers/api/results_controller.rb, app/models/arm.rb, app/models/result.rb, config/routes.rb
- [A2R-92](https://smashingboxes.atlassian.net/browse/A2R-92)
- Created API to fetch user's "Pharmacokinetics & Pharmacodynamics" for CTR.
- Created API to Update user's "Pharmacokinetics & Pharmacodynamics" for CTR.
**APIs**
Fetch User CTR Pharmacokinetics & Pharmacodynamics API
GET /api/results/pharmacokinetics_pharmacodynamics?auth_token=UgpnXf9c64wb5VmTXHdIvw&result_id=5f41d7c1d765b802e4f91a71
Return JSON
{
"arms": [
{
"id": "5f4f2befd765b802667dd312",
"dose_limiting_toxicities": {
"dose_level": "1",
"dose_drug_1": "1",
"dose_drug_2": "1",
"enrolled": "10",
"cmax_mean": "5",
"tmax_range": "1 - 3",
"auc": "5",
"t_mean": "3",
"cif_mean": "2"
}
}
],
"comments": []
}
Update User CTR Pharmacokinetics & Pharmacodynamics API Phase I/II
POST …
=> NR_A2R_92: Back End Pharmacokinetics & Pharmacodynamics

app/controllers/api/results_controller.rb, app/models/adverse_event.rb, app/models/arm.rb, app/models/category.rb, app/models/event.rb, app/models/events_table.rb, app/models/result.rb, config/adverse_events.yml, config/categories.yml, config/routes.rb
- [A2R-86](https://smashingboxes.atlassian.net/browse/A2R-86)
- Created API to fetch user's "Adverse Events" for CTR.
- Created API to Update user's "Adverse Events" for CTR.
**APIs**
Fetch User CTR Adverse Events API
GET /api/results/adverse_events?auth_token=UgpnXf9c64wb5VmTXHdIvw&result_id=5f41d7c1d765b802e4f91a71
Return JSON
{
"arms": [
{
"id": "5f4f2befd765b802667dd312",
"ctcae_version": 4,
"adverse_events_subtitle": "All Dose Levels, Cycle 1",
"adverse_events_number": "Number of Patients",
"adverse_events_legend": "",
"dlt": {
"columns": [
{
"id": "dose_level",
"name": "Dose Level",
"field": "dose_level"
},
{
"id": "enrolled",
"name": "Number Enrolled",
"field": "enrolled"
},
{
"id": "evaluable",
"name": "Number Evaluable for …
=> NR_A2R_86: Back End Adverse Events

app/controllers/api/results_controller.rb, app/models/arm.rb, app/models/assessment.rb, app/models/result.rb, app/models/user.rb, config/routes.rb
- [A2R-84](https://smashingboxes.atlassian.net/browse/A2R-84)
- Created API to fetch user's "Primary Assessment Method" for CTR.
- Created API to Update user's "Primary Assessment Method" for CTR.
**APIs**
Fetch User CTR Primary Assessment Method API
GET /api/results/primary_assessment_method?auth_token=UgpnXf9c64wb5VmTXHdIvw&result_id=5f41d7c1d765b802e4f91a71
Return JSON
{
"arms": [
{
"id": "5f4f2befd765b802667dd312",
"assessments": [
{
"id": "5f58ce1ed765b8025559b3ee",
"key": "primary",
"title": "Title 1",
"evaluation_method": "RECIST 1.0",
"number_of_patients": {
"screened": "1",
"enrolled": "2",
"evaluable": "3",
"evaluated": "4"
},
"response_assessment": {
"cr_n": "10",
"pr_n": "1",
"sd_n": "1",
"pd_n": "1",
"other_n": "1",
"cr": …
=> NR_A2R_84: Back End Primary Assessment Method

app/controllers/api/results_controller.rb, app/models/result.rb, app/models/user.rb, config/routes.rb
- [A2R-94](https://smashingboxes.atlassian.net/browse/A2R-94)
- Created API to fetch user's "Primary Assessment Method" for CTR.
- Created API to Update user's "Primary Assessment Method" for CTR.
**APIs**
Fetch User CTR Primary Assessment Method API
GET /api/results/assessment_analysis_discussion?auth_token=UgpnXf9c64wb5VmTXHdIvw&result_id=5f41d7c1d765b802e4f91a71
Return JSON
{
"completed_or_terminated": "Study Completed",
"investigators_assessment": "Active and should be pursued further",
"completed_reason": "Completed",
"terminated_reason": "Terminated",
"discussion": "Discussion",
"references": "References"
"comments": []
}
Update User CTR Primary Assessment Method API
PATCH /api/results
{
"section": "assessment_analysis_discussion", …
=> NR_A2R_94: Back End Assessment Analysis & Discussion

config/initializers/_settings.rb, config/settings.yml
- Created settings.yml file to store some values inside the file for security.
=> NR_A2R_98: Back end Author Forms

app/controllers/api/results_controller.rb, app/helpers/date_helper.rb, app/models/assessment.rb, app/models/figure.rb, app/models/result.rb, config/routes.rb
- [A2R-100](https://smashingboxes.atlassian.net/browse/A2R-100)
- Created API to fetch user's "Submission Overview" for CTR.
- Created API to Update user's CTR to submitted.
**APIs**
Fetch User CTR Author Forms API
GET /api/results/submission_overview?auth_token=UgpnXf9c64wb5VmTXHdIvw&result_id=5f41d7c1d765b802e4f91a71
Return JSON
{
"summary": {
"submitted_date": "First Submitted Online Unknown",
"title": "CTR Test",
"authors": [
{
"first_name": "Sam",
"last_name": "Antha"
},
{
"first_name": "",
"last_name": ""
},
{
"first_name": "",
"last_name": ""
}
],
"identifier": "CTR-123",
"sponsor": "",
"pi": [
{
"first_name": "Sam",
"last_name": "Antha"
},
{
"first_name": "",
"last_name": ""
},
{
"first_name": "",
"last_name": ""
}
], …
=> NR_A2R_100: Back End Submission Overview

app/javascript/src/components/overview/overview-form/overview-form.component.jsx
Added trim function for checking maximum word input.
=> A2R-space-fixes

app/controllers/api/results_controller.rb, app/models/result.rb, config/routes.rb
- [A2R-108](https://smashingboxes.atlassian.net/browse/A2R-108)
- Created API to change the CTR's status to submitted | in_review | revision | accepted | rejected | published.
- Added result_count to all CTR APIs and can update using the PATCH apis
**APIs**
Submit CTR API
POST /api/results/submit
{
"result_id":"5f41d7c1d765b802e4f91a71"
}
In Review CTR API
POST /api/results/in_review
{
"result_id":"5f41d7c1d765b802e4f91a71"
}
Revision CTR API
POST /api/results/revision
{
"result_id":"5f41d7c1d765b802e4f91a71"
}
Accept CTR API
POST /api/results/accepted
{
"result_id":"5f41d7c1d765b802e4f91a71"
}
Reject CTR API
POST /api/results/rejected
{
"result_id":"5f41d7c1d765b802e4f91a71"
}
Publish CTR API
POST /api/results/publish
{ …
=> NR_A2R_108: Back End Submission Workflows

app/controllers/api/results_controller.rb, app/models/result.rb, config/routes.rb
- [A2R-75](https://smashingboxes.atlassian.net/browse/A2R-75)
- Created API to fetch CTR's activity logs.
**APIs**
Submit CTR API
GET /api/results/activity_logs?result_id=5f41d7c1d765b802e4f91a71
Return JSON
{
"logs": [
{
"date": " 2:25 PM on September 12, 2020",
"user": "",
"type": "Form",
"details": null
},
{
"date": " 2:25 PM on September 12, 2020",
"user": "",
"type": "Form",
"details": null
},
{
"date": " 2:26 PM on September 12, 2020",
"user": "",
"type": "Form",
"details": null
},
{
"date": " 2:28 PM on September 12, 2020",
"user": "",
"type": "Form",
"details": null
},
{
"date": " 2:28 PM on September 12, 2020",
"user": "",
"type": "Form",
"details": null
},
{
"date": " 2:29 PM on September 12, 2020",
"user": "",
"type": "Form", …
=> NR_A2R_75: Back End Activity Log

Gemfile, Gemfile.lock, app/controllers/api/results_controller.rb, app/helpers/date_helper.rb, app/models/result.rb, app/views/results/docx_html.html.haml, config/routes.rb
- [A2R-126](https://smashingboxes.atlassian.net/browse/A2R-126)
- Created API to call the Export CTR function to download the current CTR.
- Created a function that will generate the CTR's sequence number based on the number of CTRs and the current year.
**APIs**
Download CTR API
GET /api/results/word_export?result_id=5f41d7c1d765b802e4f91a71
*Note: This API cannot be used on POSTMAN, I've tried and it doesn't download the file
Downloaded file
[ctr20-001.docx](https://github.com/smashingboxes/alphamed-ctr-www/files/5251152/ctr20-001.docx)
=> NR_A2R_126: Back End: Download View CTR Page

app/controllers/api/results_controller.rb, config/routes.rb
- [A2R-70](https://smashingboxes.atlassian.net/browse/A2R-70)
- Created API to fetch CTR's comments.
**APIs**
Fetch CTR Comments API
GET /api/results/comments?result_id=5f41d7c1d765b802e4f91a71&step=overview
Return JSON
{
"comments": [
{
"id": "5f4dd5f9d765b802ba88da45",
"content": "This is a comment",
"step": "overview",
"created_at": "2020-09-01T05:02:49.976Z",
"created_at_string": " 5:02 AM on September  1, 2020",
"user": {
"name": "Sam Antha"
}
},
{
"id": "5f4dd708d765b802ba88da46",
"content": "This is a comment update",
"step": "overview",
"created_at": "2020-09-01T05:07:20.380Z",
"created_at_string": " 5:07 AM on September  1, 2020",
"user": {
"name": "Sam Antha"
}
},
{
"id": "5f4ddffad765b803d6f94c1f",
"content": "This is a comment …
=> NR_A2R_70 Back End: Notes Page

app/controllers/api/results_controller.rb, app/controllers/results_controller.rb, app/models/result.rb, config/routes.rb
- [A2R-110](https://smashingboxes.atlassian.net/browse/A2R-110)
- Created Search CTR API to search through existing CTRs based on the text being sent.
**APIs**
Search CTR API
GET /api/results/search?query=ctr&page=1&limit=10
Return JSON
[
{
"title": "CTR Test(CTR20-001)",
"authors": [
{
"first_name": "Sam",
"last_name": "Antha",
"email": "sam.antha@gmail.com"
},
{
"first_name": "",
"last_name": "",
"email": "email1@email.com"
},
{
"first_name": "",
"last_name": "",
"email": "email2@email.com"
}
],
"submitted": "09/17/20"
}
]
=> NR_A2R_110 Back End Search

app/controllers/api/mail_templates_controller.rb, app/mailers/user_mailer.rb, config/environments/development.rb, config/initializers/devise.rb, config/routes.rb
- [A2R-119](https://smashingboxes.atlassian.net/browse/A2R-119)
- Temporarily changed the sender email to "sample@email.com"
- Changed the Send Email API.
**APIs**
Send Email API
POST /api/mail_templates/send_email
{
"user_id" : "5f37ce77d765b805d6ccd225",
"mail_template_id": "5f45ceecd765b80257c0f692"
}
Return JSON
{
"message": "Successfully sent email to John Smith."
}
=> NR A2R 119 Emails
